version: '3.1'
services:
  postgresql:
    image: postgres:14-alpine
    container_name: as-psql
    environment:
      - POSTGRES_DB=authorization
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - ps

  kit:
    image: kit:latest
    container_name: kit
    networks:
      - grpc
    ports:
      - '8080:8080'

  authorization:
    image: authorization:latest
    container_name: as-backend
    depends_on:
      - postgresql
    networks:
      - grpc
      - ps


networks:
    grpc:
    ps: